on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
    types: [created]
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        # use this version if the Docker image action continues to be updated.
        #uses: docker://codiumai/pr-agent:0.29-github_action
        uses: qodo-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # If you want to know whole configuration options, please refer to the link below.
          # https://github.com/qodo-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml
          CONFIG__MODEL: "gemini/gemini-2.5-flash" # not "MODEL" !
          GOOGLE_AI_STUDIO__GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

          PR_DESCRIPTION.GENERATE_AI_TITLE: "true"
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: "Please make the PR title follow the conventional commit format."
          PR_DESCRIPTION.PUBLISH_LABELS: "true"
